;;;; help-panel.lisp

(in-package #:monster-avengers.simple-web)

(eval-when (:compile-toplevel :load-toplevel :execute)
  (enable-jsx-reader))

(def-widget help-item (language name title)
    ()
  #jsx(:div ((class-name "panel panel-default"))
            (:div ((class-name "panel-heading")
                   (role "tab")
                   (id (+ "help-" name "-heading")))
                  (:h3 ((class-name "panel-title"))
                       (:a (("data-toggle" "collapse")
                            ("data-parent" "#help-group")
                            (href (+ "#" name "-gif"))
                            ("aria-expanded" "true")
                            ("aria-controls" "search-gif"))
                           title)))
            (:div ((class-name "panel-collapse collapse")
                   (id (+ name "-gif"))
                   (role "tabpanel")
                   ("aria-labeledby" (+ "help-" name "-heading")))
                  (:div ((class-name "panel-body"))
                        (:img ((src (+ "img/" name ".gif"))
                               (style :width "90%"
                                      :margin-left "5%")))))))

(def-widget help-panel (language)
    ()
  #jsx(:div ((class-name "panel-group")
             (id "help-group")
             (role "tablist")
             ("aria-multiselectable" "true"))
            (:help-item ((:language language)
                         (name "set_parameter")
                         (title (lang-text ("en" "Set Parameters")
                                           ("zh" "设置参数")))))
            (:help-item ((:language language)
                         (name "add_amulet")
                         (title (lang-text ("en" "Add Amulets")
                                           ("zh" "添加/删除 护石")))))
            (:help-item ((:language language)
                         (name "add_skills")
                         (title (lang-text ("en" "Add/Remove Skills")
                                           ("zh" "添加/删除 技能")))))
            (:help-item ((:language language)
                         (name "search")
                         (title (lang-text ("en" "Performing Search")
                                           ("zh" "搜索并浏览结果")))))
            (:help-item ((:language language)
                         (name "result")
                         (title (lang-text ("en" "View and Filtering Results")
                                           ("zh" "查看/过滤 搜索结果")))))))


(eval-when (:compile-toplevel :load-toplevel :execute)
  (disable-jsx-reader))
