;;;; parameter-panel.lisp

(in-package #:monster-avengers.simple-web)

(eval-when (:compile-toplevel :load-toplevel :execute)
  (enable-jsx-reader))

(def-widget parameter-panel (language weapon-type weapon-holes min-rare max-rare max-results callback)
    ()
  #jsx(:div ((class-name "row"))
            (:div ((class-name "col-md-2 col-sm-4 col-xs-4"))
                  (:div ((class-name "panel panel-default"))
                        (:div ((class-name "panel-heading"))
                              (:h3 ((class-name "panel-title"))
                                   (lang-text ("en" "Weapon")
                                              ("zh" "武器类型"))))
                        (:div ((class-name "panel-body"))
                              (:div ((class-name "row"))
                                     (:div ((class-name "col-md-6 col-xs-6 col-sm-6"))
                                           (:select ((class-name "form-control")            
                                                     (value weapon-type)
                                                     (on-change (lambda (e)
                                                                  (funcall callback "weapon-type"
                                                                           (@ e target value)))))
                                                    (:option ((value "melee"))
                                                             (lang-text ("en" "Blade")
                                                                        ("zh" "近战")))
                                                    (:option ((value "range")) 
                                                             (lang-text ("en" "Gun")
                                                                        ("zh" "远程")))))
                                     (:div ((class-name "col-md-6 col-xs-6 col-sm-6"))
                                           (:select ((class-name "form-control")
                                                     (value weapon-holes)
                                                     (on-change (lambda (e)
                                                                  (funcall callback "weapon-holes"
                                                                           (@ e target value)))))
                                                    (:option ((value "0")) "---")
                                                    (:option ((value "1")) "O")
                                                    (:option ((value "2")) "OO")
                                                    (:option ((value "3")) "OOO")))))))
            (:div ((class-name "col-md-2 col-sm-4 col-xs-4"))
                  (:div ((class-name "panel panel-default"))
                        (:div ((class-name "panel-heading"))
                              (:h3 ((class-name "panel-title"))
                                   (lang-text ("en" "Number of Answers")
                                              ("zh" "最大结果数"))))
                        (:div ((class-name "panel-body"))
                              (:select ((class-name "form-control")
                                        (value max-results)
                                        (on-change (lambda (e)
                                                     (funcall callback "max-results"
                                                              (@ e target value)))))
                                       (:option ((value "10")) "10")
                                       (:option ((value "20")) "20")
                                       (:option ((value "30")) "30")
                                       (:option ((value "40")) "40")))))
            (:div ((class-name "col-md-2 col-sm-4 col-xs-4"))
                  (:div ((class-name "panel panel-default"))
                        (:div ((class-name "panel-heading"))
                              (:h3 ((class-name "panel-title"))
                                   (lang-text ("en" "Rarity")
                                              ("zh" "稀有度"))))
                        (:div ((class-name "panel-body"))
                              (:form ((class-name "row"))
                                     (:div ((class-name "col-md-6 col-xs-6 col-sm-6"))
                                           (:div ((class-name "input-group"))
                                                 (:span ((class-name "input-group-addon")) "(")
                                                 (:select ((class-name "form-control")            
                                                           (value min-rare)
                                                           (on-change (lambda (e)
                                                                        (funcall callback "min-rare"
                                                                                 (@ e target value)))))
                                                          (:option ((value "1")) "1")
                                                          (:option ((value "2")) "2")
                                                          (:option ((value "3")) "3")
                                                          (:option ((value "4")) "4")
                                                          (:option ((value "5")) "5")
                                                          (:option ((value "6")) "6")
                                                          (:option ((value "7")) "7")
                                                          (:option ((value "8")) "8")
                                                          (:option ((value "9")) "9")
                                                          (:option ((value "10")) "10"))))
                                     (:div ((class-name "col-md-6 col-xs-6 col-sm-6"))
                                           (:div ((class-name "input-group"))
                                                 (:select ((class-name "form-control")
                                                           (value max-rare)
                                                           (on-change (lambda (e)
                                                                        (funcall callback "max-rare"
                                                                                 (@ e target value)))))
                                                          (:option ((value "1")) "1")
                                                          (:option ((value "2")) "2")
                                                          (:option ((value "3")) "3")
                                                          (:option ((value "4")) "4")
                                                          (:option ((value "5")) "5")
                                                          (:option ((value "6")) "6")
                                                          (:option ((value "7")) "7")
                                                          (:option ((value "8")) "8")
                                                          (:option ((value "9")) "9")
                                                          (:option ((value "10")) "10"))
                                                 (:span ((class-name "input-group-addon")) ")")))))))))
                                                 


(eval-when (:compile-toplevel :load-toplevel :execute)
  (disable-jsx-reader))
