;;;; parameter-panel.lisp

(in-package #:monster-avengers.simple-web)

(eval-when (:compile-toplevel :load-toplevel :execute)
  (enable-jsx-reader))

(def-widget parameter-panel (language weapon-type weapon-holes rare callback)
    ()
  #jsx(:div ((class-name "row"))
            (:div ((class-name "col-md-2"))
                  (:div ((class-name "panel panel-default"))
                        (:div ((class-name "panel-heading"))
                              (:h3 ((class-name "panel-title"))
                                   (lang-text ("en" "Weapon Type")
                                              ("zh" "武器类型"))))
                        (:div ((class-name "panel-body"))
                              (:select ((class-name "form-control")
                                        (value weapon-type)
                                        (on-change (lambda (e)
                                                     (funcall callback "weapon-type"
                                                              (@ e target value)))))
                                       (:option ((value "melee"))
                                                (lang-text ("en" "Blademaster")
                                                           ("zh" "近战")))
                                       (:option ((value "range")) 
                                                (lang-text ("en" "Gunner")
                                                           ("zh" "远程")))))))
            (:div ((class-name "col-md-2"))
                  (:div ((class-name "panel panel-default"))
                        (:div ((class-name "panel-heading"))
                              (:h3 ((class-name "panel-title"))
                                   (lang-text ("en" "Weapon Slots")
                                              ("zh" "武器孔数"))))
                        (:div ((class-name "panel-body"))
                              (:select ((class-name "form-control")
                                        (value weapon-holes)
                                        (on-change (lambda (e)
                                                     (funcall callback "weapon-holes"
                                                              (@ e target value)))))
                                       (:option ((value "0")) "---")
                                       (:option ((value "1")) "O")
                                       (:option ((value "2")) "OO")
                                       (:option ((value "3")) "OOO")))))
            (:div ((class-name "col-md-2"))
                  (:div ((class-name "panel panel-default"))
                        (:div ((class-name "panel-heading"))
                              (:h3 ((class-name "panel-title"))
                                   (lang-text ("en" "Minimum Rare")
                                              ("zh" "稀有度"))))
                        (:div ((class-name "panel-body"))
                              (:select ((class-name "form-control")
                                        (value rare)
                                        (on-change (lambda (e)
                                                     (funcall callback "rare"
                                                              (@ e target value)))))
                                       (:option ((value "1")) "1")
                                       (:option ((value "2")) "2")
                                       (:option ((value "3")) "3")
                                       (:option ((value "4")) "4")
                                       (:option ((value "5")) "5")
                                       (:option ((value "6")) "6")
                                       (:option ((value "7")) "7")
                                       (:option ((value "8")) "8")
                                       (:option ((value "9")) "9")
                                       (:option ((value "10")) "10")))))))

(eval-when (:compile-toplevel :load-toplevel :execute)
  (disable-jsx-reader))
