;;;; skill-panel.lisp

(in-package #:monster-avengers.simple-web)

(eval-when (:compile-toplevel :load-toplevel :execute)
  (enable-jsx-reader))

(def-widget skill-item (language effect update-callback destructor)
    ()
  #jsx(with-slots (name skills) (aref skill-systems (@ effect id))
	(:li ((class-name "list-group-item"))
	     (:div ((class-name "row"))
		   (:div ((class-name "col-md-4"))
                         (lang-text ("zh" (@ name jp))
                                    ("en" (@ name en))))
		   (:div ((class-name "col-md-6"))
			 (:select ((class-name "form-control")
                                   (value (@ effect active))
				   (on-change (lambda (e)
                                                (funcall update-callback
                                                         (@ effect id)
                                                         (@ e target value)))))
				  (chain skills 
					 (map (lambda (skill id)
						(:option ((value id))
							 (lang-text ("zh" (@ skill name jp))
                                                                    ("en" (@ skill name en)))))))))
		   (:div ((class-name "col-md-2"))
			 (:button ((class-name "btn btn-default")
				   (on-click (lambda () 
					       (funcall destructor (@ effect id)))))
				  (:span ((class-name "glyphicon glyphicon-remove")))))))))

(def-widget skill-panel (language change-callback effects)
    ((state (selected 1))
     (add-skill ()
		(funcall change-callback (local-state selected) 0)
		nil)
     (remove-skill (skill-id)
		   (funcall change-callback skill-id -1)
		   nil))
  #jsx(:div ((class-name "panel panel-default"))
            (:div ((class-name "panel-heading"))
                  (lang-text ("en" "Skills")
                             ("zh" "技能")))
            (:ul ((class-name "list-group"))
		 (chain effects
			(map (lambda (effect) 
			       (:skill-item ((effect effect)
                                             (:language language)
					     (update-callback change-callback)
					     (destructor (@ this remove-skill))))))))
            (:div ((class-name "panel-body"))
                  (:div ((class-name "input-group"))
                        (:select ((class-name "form-control")
                                  (value (local-state selected))
				  (on-change (lambda (e)
                                               (chain this 
                                                      (set-state (create 
                                                                  selected
                                                                  (@ e target value)))))))
                                 (chain skill-systems 
                                        (filter (lambda (skill id)
                                                  (> id 0)))
					(map (lambda (system id)
					       (:option ((value (1+ id)))
                                                        (lang-text ("zh" (@ system name jp))
                                                                   ("en" (@ system name en))))))))
                        (:div ((class-name "input-group-btn dropdown"))
                              (:button ((class-name "btn btn-default")
					(on-click (@ this add-skill)))
                                       (lang-text ("en" "Add")
                                                  ("zh" "添加"))))))))

(eval-when (:compile-toplevel :load-toplevel :execute)
  (disable-jsx-reader))
