package(default_visibility = ["//data:__subpackages__"]);

cc_library(
    name = "utils",
    deps = [
        ":enum_string",
    ],
)

cc_library(
    name = "enum_string",
    hdrs = [
        "enum_string.h",
    ],
)
