;;;; simple-web.lisp

(in-package #:monster-avengers.simple-web)

(eval-when (:compile-toplevel :load-toplevel :execute)
  (enable-jsx-reader))

;; (def-widget criteria-list ()
;;     ()
;;   #jsx(:div ((class-name "topcoat-list")
;;              (style :float "top"))
;;             (:ul ((class-name "topcoat-list__container"))
;;                  (:li ((class-name "topcoat-list__item"))
;;                       (:span ((style :display "block"))
;;                              "Attack Up"))
;;                  (:li ((class-name "topcoat-list__item")) 
;;                       "Critical Up")
;;                  (:li ((class-name "topcoat-list__item")) 
;;                       "Dodge Up"))))

;; (def-widget search-controller ()
;;     ()
;;   #jsx(:div ((class-name "topcoat-button-bar full"))
;; 	    (:div ((class-name "topcoat-button-bar__item"))
;; 		  (:button ((class-name "topcoat-button-bar__button full"))
;; 			   (:span ((class-name "icomatic"))
;; 				  "minus")))
;; 	    (:div ((class-name "topcoat-button-bar__item"))
;; 		  (:button ((class-name "topcoat-button-bar__button full"))
;; 			   (:span ((class-name "icomatic"))
;; 				  "plus")))
;; 	    (:div ((class-name "topcoat-button-bar__item"))
;; 		  (:button ((class-name "topcoat-button-bar__button full"))
;; 			   (:span ((class-name "icomatic")
;; 				   (style :color "#000055"))
;; 				  "search")))))

;; (def-widget armor-type-switch ()
;;     ()
;;   #jsx(:label ((class-name "topcoat-switch"))
;; 	      (:input ((type "checkbox")
;; 		       (class-name "topcoat-switch__input")))
;; 	      (:div ((class-name "armor-type-switch__toggle armor-type-switch__eng")))))



;; (def-widget side-bar ()
;;     ()
;;   #jsx(:div ((style :width "30%"
;;                     :min-height "1200px"
;;                     :left "0px"
;;                     :box-shadow "5px 0px 20px 0px #999"
;;                     :position "fixed"
;;                     :z-index 1
;;                     :float "left"))
;;             (:div ((class-name "topcoat-navigation-bar"))
;;                   (:div ((class-name "topcoat-navigation-bar__item two-thirds left"))
;;                         (:div ((class-name "topcoat-navigation-bar__title center")
;; 			       (style :text-shadow "0 3px 3px #888"))

;;                               (:span ((style :color "black"
;;                                              :font-size 28)) "M")
;;                               (:span ((style :color "#888888"
;;                                              :font-size 24))
;;                                      "ONSTER ")
;;                               (:span ((style :color "black"
;;                                              :font-size 28)) "A")
;;                               (:span ((style :color "#888888"
;;                                              :font-size 24))
;;                                      "VENGERS")))
;;                   (:div ((class-name "topcoat-navigation-bar__item third right"))
;;                         (:button ((class-name "topcoat-icon-button--quiet"))
;;                                  (:span ((class-name "icomatic")
;;                                          (style :color "#000055"))
;;                                         "settings"))))
;;             (:div ((class-name "topcoat-list"))
;;                   (:h3 ((class-name "topcoat-list__header")) "Criterias")
;;                   (:ul ((class-name "topcoat-list__container"))
;;                        (:li ((class-name "topcoat-list__item"))
;; 			    (:armor-type-switch))
;;                        (:li ((class-name "topcoat-list__item"))
;;                             "Attack Up")
;;                        (:li ((class-name "topcoat-list__item"))
;;                             "Dodge Up")
;;                        (:li ((class-name "topcoat-list__item"))
;;                             "Critical Up")
;;                        (:li ((class-name "topcoat-list__item"))
;; 			    (:search-controller))))))


;; (def-widget armor-view (armor-name)
;;     ()
;;   #jsx(:li ((class-name "block")
;;             (style :padding "0px"
;;                    :box-shadow "7px 7px 20px 0px #555"
;;                    :margin-left "0px"))
;;            (:label ((style :border-top "1px solid #878e98"
;;                            :display "block"
;;                            :color "#fff"
;;                            :text-shadow "0 1px 1px #000"
;;                            :padding "12px"
;;                            :background "-webkit-gradient(linear, 0% 0%, 0% 100%, from(#888888), to(#737271))"
;;                            :border-bottom "1px solid #33373d"))
;;                    (:span ((class-name "icomatic"))
;;                           "arrowright")
;;                    (+ " " armor-name))))

;; (def-widget armor-set-view ()
;;     ()
;;   #jsx(:ul ((style :min-height "300px"
;;                    :margin-left "5%"
;;                    :margin-right "5%"
;;                    :margin-top "40px"
;;                    :box-sizing "border-box"
;;                    :list-style "none"))
;;            (:armor-view ((armor-name "Helm")))
;;            (:armor-view ((armor-name "Chest Plate")))
;;            (:armor-view ((armor-name "Gloves")))
;;            (:armor-view ((armor-name "Cuisses")))
;;            (:armor-view ((armor-name "Boots")))))






;; (def-widget armor-list-view ()
;;     ()
;;   #jsx(:div ((style :width "65%"
;;                     :min-height "1200px"
;;                     :position "relative"
;;                     :margin-left "30%"
;;                     :float "left"))
;;             (:div ((style :float "right"
;;                           :width "50%"))
;;                   (:armor-set-view)
;;                   (:armor-set-view)
;;                   (:armor-set-view))
;;             (:div ((style :overflow "hidden"))
;;                   (:armor-set-view)
;;                   (:armor-set-view))))

(def-rpc answer-query (query)
  (with-open-file (cache "~/tmp/query_cache.lsp"
                          :direction :output
                          :if-exists :supersede)
    (format cache "~a~%" query))
  (json "answer"
        (let ((input (make-string-input-stream
                      (with-output-to-string (*standard-output*) 
                        (sb-ext:run-program "/home/breakds/pf/projects/monster-avengers/cpp/build/find_armor" 
                                            '("/home/breakds/pf/projects/monster-avengers/dataset/MH4G"
                                              "/home/breakds/tmp/query_cache.lsp") 
                                            :output *standard-output* :wait t)))))
          (loop for line = (read-line input nil nil)
             while line
             collect line))))

(def-widget weapon-type-input (callback)
    ()
  #jsx(:li ((class-name "list-group-item row"))
           (:div ((class-name "col-md-4"))
                 (:button ((class-name "btn btn-info btn-block disabled"))
                          "Weapon Type"))
           (:div ((class-name "col-md-6"))
                 (:select ((class-name "form-control")
                           (on-change (lambda (e) (funcall callback 
                                                           (chain e target value)))))
                          (:option ((value "melee")) "Melee")
                          (:option ((value "range")) "Range")))))

(def-widget weapon-holes-input (callback)
    ()
  #jsx(:li ((class-name "list-group-item row"))
           (:div ((class-name "col-md-4"))
                 (:button ((class-name "btn btn-info btn-block disabled"))
                          "Weapon Holes"))
           (:div ((class-name "col-md-6"))
                 (:select ((class-name "form-control")
                           (on-change (lambda (e) (funcall callback 
                                                           (chain e target value)))))
                          (:option ((value "0")) "0")
                          (:option ((value "1")) "1")
                          (:option ((value "2")) "2")
                          (:option ((value "3")) "3")))))

(def-widget rare-input (callback)
    ()
  #jsx(:li ((class-name "list-group-item row"))
           (:div ((class-name "col-md-4"))
                 (:button ((class-name "btn btn-info btn-block disabled"))
                          "Rare"))
           (:div ((class-name "col-md-6"))
                 (:select ((class-name "form-control")
                           (on-change (lambda (e) (funcall callback 
                                                           (chain e target value)))))
                          (:option ((value "0")) "0")
                          (:option ((value "1")) "1")
                          (:option ((value "2")) "2")
                          (:option ((value "3")) "3")
                          (:option ((value "4")) "4")
                          (:option ((value "5")) "5")
                          (:option ((value "6")) "6")
                          (:option ((value "7")) "7")
                          (:option ((value "8")) "8")
                          (:option ((value "9")) "9")
                          (:option ((value "10")) "10")))))

(def-widget skill-input (effect-id id-callback points-callback)
    ()
  #jsx(:li ((class-name "list-group-item row"))
           (:div ((class-name "col-md-4"))
                 (:button ((class-name "btn btn-success btn-block disabled"))
                          "Skill"))
           (:div ((class-name "col-md-3"))
                 (:select ((class-name "form-control")
                           (on-change (lambda (e) (funcall id-callback
                                                           effect-id
                                                           (chain e target value)))))
                          (:option ((value 0)) "裂傷")
                          (:option ((value 1)) "榴弾追加")
                          (:option ((value 2)) "龍耐性")
                          (:option ((value 3)) "龍属性攻撃")
                          (:option ((value 4)) "無傷")
                          (:option ((value 5)) "水耐性")
                          (:option ((value 6)) "水属性攻撃")
                          (:option ((value 7)) "麻痺瓶追加")
                          (:option ((value 8)) "麻痺")
                          (:option ((value 9)) "本気")
                          (:option ((value 10)) "北辰納豆流")
                          (:option ((value 11)) "捕獲")
                          (:option ((value 12)) "砲術")
                          (:option ((value 13)) "防御")
                          (:option ((value 14)) "不動")
                          (:option ((value 15)) "笛")
                          (:option ((value 16)) "風圧")
                          (:option ((value 17)) "秘伝")
                          (:option ((value 18)) "火耐性")
                          (:option ((value 19)) "火属性攻撃")
                          (:option ((value 20)) "反動")
                          (:option ((value 21)) "腹減り")
                          (:option ((value 22)) "抜刀減気")
                          (:option ((value 23)) "抜刀会心")
                          (:option ((value 24)) "ハチミツ")
                          (:option ((value 25)) "爆破瓶追加")
                          (:option ((value 26)) "爆破弾追加")
                          (:option ((value 27)) "爆弾強化")
                          (:option ((value 28)) "剥ぎ取り")
                          (:option ((value 29)) "乗り")
                          (:option ((value 30)) "納刀")
                          (:option ((value 31)) "燃鱗")
                          (:option ((value 32)) "盗み無効")
                          (:option ((value 33)) "肉食")
                          (:option ((value 34)) "毒瓶追加")
                          (:option ((value 35)) "特殊攻撃")
                          (:option ((value 36)) "特殊会心")
                          (:option ((value 37)) "毒")
                          (:option ((value 38)) "研ぎ師")
                          (:option ((value 39)) "刀匠")
                          (:option ((value 40)) "闘魂")
                          (:option ((value 41)) "胴系統倍加")
                          (:option ((value 42)) "通常弾追加")
                          (:option ((value 43)) "通常弾強化")
                          (:option ((value 44)) "痛撃")
                          (:option ((value 45)) "調合成功率")
                          (:option ((value 46)) "調合数")
                          (:option ((value 47)) "聴覚保護")
                          (:option ((value 48)) "溜め短縮")
                          (:option ((value 49)) "盾持")
                          (:option ((value 50)) "達人")
                          (:option ((value 51)) "匠")
                          (:option ((value 52)) "体力")
                          (:option ((value 53)) "対防御DOWN")
                          (:option ((value 54)) "耐粘")
                          (:option ((value 55)) "耐泥耐雪")
                          (:option ((value 56)) "耐震")
                          (:option ((value 57)) "耐暑")
                          (:option ((value 58)) "体術")
                          (:option ((value 59)) "耐寒")
                          (:option ((value 60)) "底力")
                          (:option ((value 61)) "属性耐性")
                          (:option ((value 62)) "属性攻撃")
                          (:option ((value 63)) "属性解放")
                          (:option ((value 64)) "属性会心")
                          (:option ((value 65)) "速射")
                          (:option ((value 66)) "増幅")
                          (:option ((value 67)) "装填速度")
                          (:option ((value 68)) "装填数")
                          (:option ((value 69)) "千里眼")
                          (:option ((value 70)) "節食")
                          (:option ((value 71)) "接撃瓶追加")
                          (:option ((value 72)) "精密射撃")
                          (:option ((value 73)) "スタミナ")
                          (:option ((value 74)) "睡眠瓶追加")
                          (:option ((value 75)) "睡眠")
                          (:option ((value 76)) "食欲")
                          (:option ((value 77)) "食事")
                          (:option ((value 78)) "職工")
                          (:option ((value 79)) "状態耐性")
                          (:option ((value 80)) "重撃")
                          (:option ((value 81)) "射法")
                          (:option ((value 82)) "射手")
                          (:option ((value 83)) "自動防御")
                          (:option ((value 84)) "指揮")
                          (:option ((value 85)) "斬裂弾追加")
                          (:option ((value 86)) "散弾追加")
                          (:option ((value 87)) "散弾強化")
                          (:option ((value 88)) "斬術")
                          (:option ((value 89)) "采配")
                          (:option ((value 90)) "採取")
                          (:option ((value 91)) "細菌学")
                          (:option ((value 92)) "根性")
                          (:option ((value 93)) "護石収集")
                          (:option ((value 94)) "護石王")
                          (:option ((value 95)) "氷耐性")
                          (:option ((value 96)) "氷属性攻撃")
                          (:option ((value 97)) "剛腕")
                          (:option ((value 98)) "号令")
                          (:option ((value 99)) "強欲")
                          (:option ((value 100)) "高速設置")
                          (:option ((value 101)) "高速収集")
                          (:option ((value 102)) "剛撃")
                          (:option ((value 103)) "攻撃")
                          (:option ((value 104)) "効果持続")
                          (:option ((value 105)) "広域")
                          (:option ((value 106)) "剣術")
                          (:option ((value 107)) "減気瓶追加")
                          (:option ((value 108)) "減気攻撃")
                          (:option ((value 109)) "気配")
                          (:option ((value 110)) "潔癖")
                          (:option ((value 111)) "KO")
                          (:option ((value 112)) "食いしん坊")
                          (:option ((value 113)) "斬れ味")
                          (:option ((value 114)) "気力回復")
                          (:option ((value 115)) "強撃瓶追加")
                          (:option ((value 116)) "狂撃耐性")
                          (:option ((value 117)) "逆境")
                          (:option ((value 118)) "気まぐれ")
                          (:option ((value 119)) "茸食")
                          (:option ((value 120)) "気絶")
                          (:option ((value 121)) "祈願")
                          (:option ((value 122)) "貫通弾追加")
                          (:option ((value 123)) "貫通弾強化")
                          (:option ((value 124)) "観察眼")
                          (:option ((value 125)) "頑強")
                          (:option ((value 126)) "狩人")
                          (:option ((value 127)) "雷耐性")
                          (:option ((value 128)) "雷属性攻撃")
                          (:option ((value 129)) "加護")
                          (:option ((value 130)) "拡散弾追加")
                          (:option ((value 131)) "回復量")
                          (:option ((value 132)) "回復速度")
                          (:option ((value 133)) "回避性能")
                          (:option ((value 134)) "回避術")
                          (:option ((value 135)) "回避距離")
                          (:option ((value 136)) "ガード性能")
                          (:option ((value 137)) "ガード強化")
                          (:option ((value 138)) "運搬")
                          (:option ((value 139)) "運気")
                          (:option ((value 140)) "裏稼業")
                          (:option ((value 141)) "一心")
                          (:option ((value 142)) "怒")
                          (:option ((value 143)) "居合")))
           (:div ((class-name "col-md-3"))
                 (:select ((class-name "form-control")
                           (on-change (lambda (e) (funcall points-callback 
                                                           effect-id
                                                           (chain e target value)))))
                          (:option ((value "0")) "0")
                          (:option ((value "1")) "1")
                          (:option ((value "2")) "2")
                          (:option ((value "3")) "3")
                          (:option ((value "4")) "4")
                          (:option ((value "5")) "5")
                          (:option ((value "6")) "6")
                          (:option ((value "7")) "7")
                          (:option ((value "8")) "8")
                          (:option ((value "9")) "9")
                          (:option ((value "10")) "10")
                          (:option ((value "11")) "11")
                          (:option ((value "12")) "12")
                          (:option ((value "13")) "13")
                          (:option ((value "14")) "14")
                          (:option ((value "15")) "15")
                          (:option ((value "16")) "16")
                          (:option ((value "17")) "17")
                          (:option ((value "18")) "18")
                          (:option ((value "19")) "19")
                          (:option ((value "20")) "20")))))

(def-widget amulet-input (amulet-id amulet-hole-callback
                                    amulet-skill-id-1-callback
                                    amulet-skill-points-1-callback
                                    amulet-skill-id-2-callback
                                    amulet-skill-points-2-callback)
    ()
  #jsx(:li ((class-name "list-group-item"))
           (:div ((class-name "row"))
                 (:div ((class-name "col-md-4"))
                       (:button ((class-name "btn btn-warning btn-block disabled"))
                                "Amulet"))
                 (:div ((class-name "col-md-4"))
                       (:select ((class-name "form-control")
                                 (on-change (lambda (e) (funcall amulet-hole-callback
                                                                 amulet-id
                                                                 (chain e target value)))))
                                (:option ((value 0)) "0孔")
                                (:option ((value 1)) "1孔")
                                (:option ((value 2)) "2孔")
                                (:option ((value 3)) "3孔"))))
           (:div ((class-name "row"))
                 (:div ((class-name "col-md-4 col-md-offset-4"))
                       (:select ((class-name "form-control")
                                 (on-change (lambda (e) (funcall amulet-skill-id-1-callback
                                                                 amulet-id
                                                                 (chain e target value)))))
                                (:option ((value 0)) "裂傷")
                                (:option ((value 1)) "榴弾追加")
                                (:option ((value 2)) "龍耐性")
                                (:option ((value 3)) "龍属性攻撃")
                                (:option ((value 4)) "無傷")
                                (:option ((value 5)) "水耐性")
                                (:option ((value 6)) "水属性攻撃")
                                (:option ((value 7)) "麻痺瓶追加")
                                (:option ((value 8)) "麻痺")
                                (:option ((value 9)) "本気")
                                (:option ((value 10)) "北辰納豆流")
                                (:option ((value 11)) "捕獲")
                                (:option ((value 12)) "砲術")
                                (:option ((value 13)) "防御")
                                (:option ((value 14)) "不動")
                                (:option ((value 15)) "笛")
                                (:option ((value 16)) "風圧")
                                (:option ((value 17)) "秘伝")
                                (:option ((value 18)) "火耐性")
                                (:option ((value 19)) "火属性攻撃")
                                (:option ((value 20)) "反動")
                                (:option ((value 21)) "腹減り")
                                (:option ((value 22)) "抜刀減気")
                                (:option ((value 23)) "抜刀会心")
                                (:option ((value 24)) "ハチミツ")
                                (:option ((value 25)) "爆破瓶追加")
                                (:option ((value 26)) "爆破弾追加")
                                (:option ((value 27)) "爆弾強化")
                                (:option ((value 28)) "剥ぎ取り")
                                (:option ((value 29)) "乗り")
                                (:option ((value 30)) "納刀")
                                (:option ((value 31)) "燃鱗")
                                (:option ((value 32)) "盗み無効")
                                (:option ((value 33)) "肉食")
                                (:option ((value 34)) "毒瓶追加")
                                (:option ((value 35)) "特殊攻撃")
                                (:option ((value 36)) "特殊会心")
                                (:option ((value 37)) "毒")
                                (:option ((value 38)) "研ぎ師")
                                (:option ((value 39)) "刀匠")
                                (:option ((value 40)) "闘魂")
                                (:option ((value 41)) "胴系統倍加")
                                (:option ((value 42)) "通常弾追加")
                                (:option ((value 43)) "通常弾強化")
                                (:option ((value 44)) "痛撃")
                                (:option ((value 45)) "調合成功率")
                                (:option ((value 46)) "調合数")
                                (:option ((value 47)) "聴覚保護")
                                (:option ((value 48)) "溜め短縮")
                                (:option ((value 49)) "盾持")
                                (:option ((value 50)) "達人")
                                (:option ((value 51)) "匠")
                                (:option ((value 52)) "体力")
                                (:option ((value 53)) "対防御DOWN")
                                (:option ((value 54)) "耐粘")
                                (:option ((value 55)) "耐泥耐雪")
                                (:option ((value 56)) "耐震")
                                (:option ((value 57)) "耐暑")
                                (:option ((value 58)) "体術")
                                (:option ((value 59)) "耐寒")
                                (:option ((value 60)) "底力")
                                (:option ((value 61)) "属性耐性")
                                (:option ((value 62)) "属性攻撃")
                                (:option ((value 63)) "属性解放")
                                (:option ((value 64)) "属性会心")
                                (:option ((value 65)) "速射")
                                (:option ((value 66)) "増幅")
                                (:option ((value 67)) "装填速度")
                                (:option ((value 68)) "装填数")
                                (:option ((value 69)) "千里眼")
                                (:option ((value 70)) "節食")
                                (:option ((value 71)) "接撃瓶追加")
                                (:option ((value 72)) "精密射撃")
                                (:option ((value 73)) "スタミナ")
                                (:option ((value 74)) "睡眠瓶追加")
                                (:option ((value 75)) "睡眠")
                                (:option ((value 76)) "食欲")
                                (:option ((value 77)) "食事")
                                (:option ((value 78)) "職工")
                                (:option ((value 79)) "状態耐性")
                                (:option ((value 80)) "重撃")
                                (:option ((value 81)) "射法")
                                (:option ((value 82)) "射手")
                                (:option ((value 83)) "自動防御")
                                (:option ((value 84)) "指揮")
                                (:option ((value 85)) "斬裂弾追加")
                                (:option ((value 86)) "散弾追加")
                                (:option ((value 87)) "散弾強化")
                                (:option ((value 88)) "斬術")
                                (:option ((value 89)) "采配")
                                (:option ((value 90)) "採取")
                                (:option ((value 91)) "細菌学")
                                (:option ((value 92)) "根性")
                                (:option ((value 93)) "護石収集")
                                (:option ((value 94)) "護石王")
                                (:option ((value 95)) "氷耐性")
                                (:option ((value 96)) "氷属性攻撃")
                                (:option ((value 97)) "剛腕")
                                (:option ((value 98)) "号令")
                                (:option ((value 99)) "強欲")
                                (:option ((value 100)) "高速設置")
                                (:option ((value 101)) "高速収集")
                                (:option ((value 102)) "剛撃")
                                (:option ((value 103)) "攻撃")
                                (:option ((value 104)) "効果持続")
                                (:option ((value 105)) "広域")
                                (:option ((value 106)) "剣術")
                                (:option ((value 107)) "減気瓶追加")
                                (:option ((value 108)) "減気攻撃")
                                (:option ((value 109)) "気配")
                                (:option ((value 110)) "潔癖")
                                (:option ((value 111)) "KO")
                                (:option ((value 112)) "食いしん坊")
                                (:option ((value 113)) "斬れ味")
                                (:option ((value 114)) "気力回復")
                                (:option ((value 115)) "強撃瓶追加")
                                (:option ((value 116)) "狂撃耐性")
                                (:option ((value 117)) "逆境")
                                (:option ((value 118)) "気まぐれ")
                                (:option ((value 119)) "茸食")
                                (:option ((value 120)) "気絶")
                                (:option ((value 121)) "祈願")
                                (:option ((value 122)) "貫通弾追加")
                                (:option ((value 123)) "貫通弾強化")
                                (:option ((value 124)) "観察眼")
                                (:option ((value 125)) "頑強")
                                (:option ((value 126)) "狩人")
                                (:option ((value 127)) "雷耐性")
                                (:option ((value 128)) "雷属性攻撃")
                                (:option ((value 129)) "加護")
                                (:option ((value 130)) "拡散弾追加")
                                (:option ((value 131)) "回復量")
                                (:option ((value 132)) "回復速度")
                                (:option ((value 133)) "回避性能")
                                (:option ((value 134)) "回避術")
                                (:option ((value 135)) "回避距離")
                                (:option ((value 136)) "ガード性能")
                                (:option ((value 137)) "ガード強化")
                                (:option ((value 138)) "運搬")
                                (:option ((value 139)) "運気")
                                (:option ((value 140)) "裏稼業")
                                (:option ((value 141)) "一心")
                                (:option ((value 142)) "怒")
                                (:option ((value 143)) "居合")))
                 (:div ((class-name "col-md-2"))
                       (:select ((class-name "form-control")
                                 (on-change (lambda (e) (funcall amulet-skill-points-1-callback
                                                                 amulet-id
                                                                 (chain e target value)))))
                                (:option ((value "0")) "0")
                                (:option ((value "1")) "1")
                                (:option ((value "2")) "2")
                                (:option ((value "3")) "3")
                                (:option ((value "4")) "4")
                                (:option ((value "5")) "5")
                                (:option ((value "6")) "6")
                                (:option ((value "7")) "7")
                                (:option ((value "8")) "8")
                                (:option ((value "9")) "9")
                                (:option ((value "10")) "10")
                                (:option ((value "11")) "11")
                                (:option ((value "12")) "12")
                                (:option ((value "13")) "13")
                                (:option ((value "14")) "14")
                                (:option ((value "15")) "15")
                                (:option ((value "16")) "16")
                                (:option ((value "17")) "17")
                                (:option ((value "18")) "18")
                                (:option ((value "19")) "19")
                                (:option ((value "20")) "20"))))
           (:div ((class-name "row"))
                 (:div ((class-name "col-md-4 col-md-offset-4"))
                       (:select ((class-name "form-control")
                                 (on-change (lambda (e) (funcall amulet-skill-id-2-callback
                                                                 amulet-id
                                                                 (chain e target value)))))
                                (:option ((value -1)) "empty")
                                (:option ((value 0)) "裂傷")
                                (:option ((value 1)) "榴弾追加")
                                (:option ((value 2)) "龍耐性")
                                (:option ((value 3)) "龍属性攻撃")
                                (:option ((value 4)) "無傷")
                                (:option ((value 5)) "水耐性")
                                (:option ((value 6)) "水属性攻撃")
                                (:option ((value 7)) "麻痺瓶追加")
                                (:option ((value 8)) "麻痺")
                                (:option ((value 9)) "本気")
                                (:option ((value 10)) "北辰納豆流")
                                (:option ((value 11)) "捕獲")
                                (:option ((value 12)) "砲術")
                                (:option ((value 13)) "防御")
                                (:option ((value 14)) "不動")
                                (:option ((value 15)) "笛")
                                (:option ((value 16)) "風圧")
                                (:option ((value 17)) "秘伝")
                                (:option ((value 18)) "火耐性")
                                (:option ((value 19)) "火属性攻撃")
                                (:option ((value 20)) "反動")
                                (:option ((value 21)) "腹減り")
                                (:option ((value 22)) "抜刀減気")
                                (:option ((value 23)) "抜刀会心")
                                (:option ((value 24)) "ハチミツ")
                                (:option ((value 25)) "爆破瓶追加")
                                (:option ((value 26)) "爆破弾追加")
                                (:option ((value 27)) "爆弾強化")
                                (:option ((value 28)) "剥ぎ取り")
                                (:option ((value 29)) "乗り")
                                (:option ((value 30)) "納刀")
                                (:option ((value 31)) "燃鱗")
                                (:option ((value 32)) "盗み無効")
                                (:option ((value 33)) "肉食")
                                (:option ((value 34)) "毒瓶追加")
                                (:option ((value 35)) "特殊攻撃")
                                (:option ((value 36)) "特殊会心")
                                (:option ((value 37)) "毒")
                                (:option ((value 38)) "研ぎ師")
                                (:option ((value 39)) "刀匠")
                                (:option ((value 40)) "闘魂")
                                (:option ((value 41)) "胴系統倍加")
                                (:option ((value 42)) "通常弾追加")
                                (:option ((value 43)) "通常弾強化")
                                (:option ((value 44)) "痛撃")
                                (:option ((value 45)) "調合成功率")
                                (:option ((value 46)) "調合数")
                                (:option ((value 47)) "聴覚保護")
                                (:option ((value 48)) "溜め短縮")
                                (:option ((value 49)) "盾持")
                                (:option ((value 50)) "達人")
                                (:option ((value 51)) "匠")
                                (:option ((value 52)) "体力")
                                (:option ((value 53)) "対防御DOWN")
                                (:option ((value 54)) "耐粘")
                                (:option ((value 55)) "耐泥耐雪")
                                (:option ((value 56)) "耐震")
                                (:option ((value 57)) "耐暑")
                                (:option ((value 58)) "体術")
                                (:option ((value 59)) "耐寒")
                                (:option ((value 60)) "底力")
                                (:option ((value 61)) "属性耐性")
                                (:option ((value 62)) "属性攻撃")
                                (:option ((value 63)) "属性解放")
                                (:option ((value 64)) "属性会心")
                                (:option ((value 65)) "速射")
                                (:option ((value 66)) "増幅")
                                (:option ((value 67)) "装填速度")
                                (:option ((value 68)) "装填数")
                                (:option ((value 69)) "千里眼")
                                (:option ((value 70)) "節食")
                                (:option ((value 71)) "接撃瓶追加")
                                (:option ((value 72)) "精密射撃")
                                (:option ((value 73)) "スタミナ")
                                (:option ((value 74)) "睡眠瓶追加")
                                (:option ((value 75)) "睡眠")
                                (:option ((value 76)) "食欲")
                                (:option ((value 77)) "食事")
                                (:option ((value 78)) "職工")
                                (:option ((value 79)) "状態耐性")
                                (:option ((value 80)) "重撃")
                                (:option ((value 81)) "射法")
                                (:option ((value 82)) "射手")
                                (:option ((value 83)) "自動防御")
                                (:option ((value 84)) "指揮")
                                (:option ((value 85)) "斬裂弾追加")
                                (:option ((value 86)) "散弾追加")
                                (:option ((value 87)) "散弾強化")
                                (:option ((value 88)) "斬術")
                                (:option ((value 89)) "采配")
                                (:option ((value 90)) "採取")
                                (:option ((value 91)) "細菌学")
                                (:option ((value 92)) "根性")
                                (:option ((value 93)) "護石収集")
                                (:option ((value 94)) "護石王")
                                (:option ((value 95)) "氷耐性")
                                (:option ((value 96)) "氷属性攻撃")
                                (:option ((value 97)) "剛腕")
                                (:option ((value 98)) "号令")
                                (:option ((value 99)) "強欲")
                                (:option ((value 100)) "高速設置")
                                (:option ((value 101)) "高速収集")
                                (:option ((value 102)) "剛撃")
                                (:option ((value 103)) "攻撃")
                                (:option ((value 104)) "効果持続")
                                (:option ((value 105)) "広域")
                                (:option ((value 106)) "剣術")
                                (:option ((value 107)) "減気瓶追加")
                                (:option ((value 108)) "減気攻撃")
                                (:option ((value 109)) "気配")
                                (:option ((value 110)) "潔癖")
                                (:option ((value 111)) "KO")
                                (:option ((value 112)) "食いしん坊")
                                (:option ((value 113)) "斬れ味")
                                (:option ((value 114)) "気力回復")
                                (:option ((value 115)) "強撃瓶追加")
                                (:option ((value 116)) "狂撃耐性")
                                (:option ((value 117)) "逆境")
                                (:option ((value 118)) "気まぐれ")
                                (:option ((value 119)) "茸食")
                                (:option ((value 120)) "気絶")
                                (:option ((value 121)) "祈願")
                                (:option ((value 122)) "貫通弾追加")
                                (:option ((value 123)) "貫通弾強化")
                                (:option ((value 124)) "観察眼")
                                (:option ((value 125)) "頑強")
                                (:option ((value 126)) "狩人")
                                (:option ((value 127)) "雷耐性")
                                (:option ((value 128)) "雷属性攻撃")
                                (:option ((value 129)) "加護")
                                (:option ((value 130)) "拡散弾追加")
                                (:option ((value 131)) "回復量")
                                (:option ((value 132)) "回復速度")
                                (:option ((value 133)) "回避性能")
                                (:option ((value 134)) "回避術")
                                (:option ((value 135)) "回避距離")
                                (:option ((value 136)) "ガード性能")
                                (:option ((value 137)) "ガード強化")
                                (:option ((value 138)) "運搬")
                                (:option ((value 139)) "運気")
                                (:option ((value 140)) "裏稼業")
                                (:option ((value 141)) "一心")
                                (:option ((value 142)) "怒")
                                (:option ((value 143)) "居合")))
                 (:div ((class-name "col-md-2"))
                       (:select ((class-name "form-control")
                                 (on-change (lambda (e) (funcall amulet-skill-points-2-callback
                                                                 amulet-id
                                                                 (chain e target value)))))
                                (:option ((value "0")) "0")
                                (:option ((value "1")) "1")
                                (:option ((value "2")) "2")
                                (:option ((value "3")) "3")
                                (:option ((value "4")) "4")
                                (:option ((value "5")) "5")
                                (:option ((value "6")) "6")
                                (:option ((value "7")) "7")
                                (:option ((value "8")) "8")
                                (:option ((value "9")) "9")
                                (:option ((value "10")) "10")
                                (:option ((value "11")) "11")
                                (:option ((value "12")) "12")
                                (:option ((value "13")) "13")
                                (:option ((value "14")) "14")
                                (:option ((value "15")) "15")
                                (:option ((value "16")) "16")
                                (:option ((value "17")) "17")
                                (:option ((value "18")) "18")
                                (:option ((value "19")) "19")
                                (:option ((value "20")) "20"))))))

(def-widget app-view ()
    ((state (weapon "melee")
            (weapon-holes 0)
            (rare 0)
            (skills (array))
            (amulets (array))
            (query-result []))
     (change-weapon-type (x) 
                         (chain this (set-state (create weapon x)))
                         nil)
     (change-weapon-holes (x)
                          (chain this (set-state (create weapon-holes x)))
                          nil)
     (change-rare (x) (chain this (set-state (create rare x))) nil)
     (update-skill-id (effect-id skill-id)
                      (let ((original-skills (local-state skills)))
                        (setf (@ (aref original-skills effect-id) id)
                              skill-id)
                        (chain this (set-state (create skills original-skills)))))
     (update-skill-points (effect-id points)
                          (let ((original-skills (local-state skills)))
                            (setf (@ (aref original-skills effect-id) points)
                                  points)
                            (chain this (set-state (create skills original-skills)))))
     (update-amulet-holes (amulet-id holes)
                          (let ((original-amulets (local-state amulets)))
                            (setf (@ (aref original-amulets amulet-id) holes)
                                  holes)
                            (chain this (set-state (create amulets original-amulets)))))
     (update-amulet-skill-id-a (amulet-id id)
                               (let ((original-amulets (local-state amulets)))
                                 (setf (@ (aref original-amulets amulet-id) id-a)
                                       id)
                                 (chain this (set-state (create amulets original-amulets)))))
     (update-amulet-skill-id-b (amulet-id id)
                               (let ((original-amulets (local-state amulets)))
                                 (setf (@ (aref original-amulets amulet-id) id-b)
                                       id)
                                 (chain this (set-state (create amulets original-amulets)))))
     (update-amulet-skill-points-a (amulet-id points)
                                   (let ((original-amulets (local-state amulets)))
                                     (setf (@ (aref original-amulets amulet-id) points-a)
                                           points)
                                     (chain this (set-state (create amulets original-amulets)))))
     (update-amulet-skill-points-b (amulet-id points)
                                   (let ((original-amulets (local-state amulets)))
                                     (setf (@ (aref original-amulets amulet-id) points-b)
                                           points)
                                     (chain this (set-state (create amulets original-amulets)))))
     (add-skill ()
                (let ((original-skills (local-state skills)))
                  (chain original-skills (push (create id 0 points 0)))
                  (chain this (set-state (create skills original-skills)))
                  nil))
     (add-amulet ()
                 (let ((original-amulets (local-state amulets)))
                   (chain original-amulets (push (create holes 0
                                                         id-a 0
                                                         points-a 0
                                                         id-b -1
                                                         points-b 0)))
                   (chain this (set-state (create amulets original-amulets)))
                   nil))
     (send-query ()
                 (let ((query (+ "(:weapon-type \"" 
                                            (local-state weapon)
                                            "\") "
                                            "(:rare "
                                            (local-state rare)
                                            ") "
                                            "(:weapon-holes "
                                            (local-state weapon-holes)
                                            ") ")))
                   (loop for skill in (local-state skills)
                      do (setf query (+ query "(:skill "
                                        (@ skill id) " "
                                        (@ skill points) ") ")))
                   (loop for amulet in (local-state amulets)
                      do (if (= -1 (@ amulet id-b)) 
                             (setf query (+ query "(:amulet "
                                            (@ amulet holes) " ("
                                            (@ amulet id-a) " "
                                            (@ amulet points-a) ")) "))
                             (setf query (+ query "(:amulet "
                                            (@ amulet holes) " ("
                                            (@ amulet id-a) " "
                                            (@ amulet points-a) " "
                                            (@ amulet id-b) " "
                                            (@ amulet points-b) ")) "))))
                   (with-rpc (answer-query query)
                     (chain this (set-state (create query-result
                                                    (@ rpc-result answer))))))))
  
  #jsx(:div ((class-name "row"))
            (:div ((class-name "col-md-4"))
                  (:h3 () "MH4G Armor Tools")
                  (:ul ((class-name "list-group"))
                       (:weapon-type-input ((callback (chain this change-weapon-type))))
                       (:weapon-holes-input ((callback (chain this change-weapon-holes))))
                       (:rare-input ((callback (chain this change-rare)))))
                  (:ul ((class-name "list-group"))
                       (chain (local-state skills)
                              (map (lambda (skill effect-id)
                                     (:skill-input ((effect-id effect-id)
                                                    (id-callback (@ this update-skill-id))
                                                    (points-callback (@ this update-skill-points))))))))
                  (:ul ((class-name "list-group"))
                       (chain (local-state amulets)
                              (map (lambda (skill amulet-id)
                                     (:amulet-input ((amulet-id amulet-id)
                                                     (amulet-hole-callback 
                                                      (@ this update-amulet-holes))
                                                     (amulet-skill-id-1-callback
                                                      (@ this update-amulet-skill-id-a))
                                                     (amulet-skill-points-1-callback
                                                      (@ this update-amulet-skill-points-a))
                                                     (amulet-skill-id-2-callback
                                                      (@ this update-amulet-skill-id-b))
                                                     (amulet-skill-points-2-callback
                                                      (@ this update-amulet-skill-points-b))))))))
                  (:div ((class-name "btn-group")
                         (role "group"))
                        (:button ((class-name "btn btn-success") (type "button")
                                  (on-click (@ this add-skill)))
                                 (:span ((class-name "glyphicon glyphicon-plus") 
                                         (aria-hidden="true">)))
                                 " Skill")
                        (:button ((class-name "btn btn-warning") (type "button")
                                  (on-click (@ this add-amulet)))
                                 (:span ((class-name "glyphicon glyphicon-plus") 
                                         (aria-hidden="true">)))
                                 " Amulet")
                        (:button ((class-name "btn btn-primary") (type "button")
                                  (on-click (@ this send-query)))
                                 (:span ((class-name "glyphicon glyphicon-search") 
                                         (aria-hidden="true">)))
                                 " Search"))
                  (:p () "built with "
                      (:a ((href "http://getbootstrap.com/")) "Twitter Bootstrap")
                      " and "
                      (:a ((href "https://github.com/breakds/realispic")) "realispic")
                      "."))
            (:div ((class-name "col-md-8"))
                  (:ul ((class-name "list-group"))
                       (chain (local-state query-result)
                              (map (lambda (line)
                                     (:li ((class-name "list-group-item")
                                           (style :font-family "monospace"))
                                          (if (= "" line)
                                              "==========================="
                                              line)))))))))

(def-realispic-app (armor-tools :title "Monster Hunter's Arsenal"
                                :port 16384
                                :css ("https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.2/css/bootstrap.min.css")
                                :libs ("http://fb.me/react-0.12.2.min.js"
                                       "https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"
                                       "https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.2/js/bootstrap.min.js")
                                :document-base (merge-pathnames "assets/"
                                                                (asdf:system-source-directory 'monster-avengers)))
  #jsx(:app-view))

(eval-when (:compile-toplevel :load-toplevel :execute)
  (disable-jsx-reader))
