;;;; simple-web.lisp

(in-package #:monster-avengers.simple-web)

(eval-when (:compile-toplevel :load-toplevel :execute)
  (defparameter *working-dir* "/home/breakds/tmp/")
  (defparameter *server-binary*
    (merge-pathnames "cpp/build/serve_query"
                     (asdf:system-source-directory 'monster-avengers)))
  (defparameter *dataset-path* 
    (merge-pathnames "dataset/MH4G/"
                     (asdf:system-source-directory 'monster-avengers))))

(eval-when (:compile-toplevel :load-toplevel :execute)
  (defpsmacro lang-text (&rest lang-text-pairs)
    `(funcall (lambda (language)
                (case language
                  ,@lang-text-pairs))
              (@ this props language))))

(eval-when (:compile-toplevel :load-toplevel :execute)
  (enable-jsx-reader))

(defun json-armor-object (obj)
  (json "name" (getf obj :name)
        "id" (getf obj :id)
        "holes" (getf obj :holes)
        "rare" (if (getf obj :rare)
                   (format nil "~2,'0d" (getf obj :rare))
                   "??")
        "material" (getf obj :material)))

(defun json-amulet-object (obj)
  (json "holes" (getf obj :holes)
        "id" (getf obj :id)
        "material" ""
        "rare" "??"
        "name" (let ((name ""))
                 (loop for effect in (getf obj :effects)
                    do (setf name (concatenate 'string name 
                                               (getf effect :name)
                                               (if (> (getf effect :points) 0)
                                                   " +" " ")
                                               (format nil "~a" (getf effect :points))
                                               "   ")))
                 name)))

(def-rpc answer-query (query)
  (let ((query-file (merge-pathnames (format nil "query_cache_~a.lsp"
                                             (hunchentoot:session-id 
                                              current-session))
                                     *working-dir*))
        (output-file (merge-pathnames (format nil "output_~a.lsp"
                                              (hunchentoot:session-id 
                                               current-session))
                                      *working-dir*)))
    (with-open-file (output output-file
                            :direction :output
                            :if-exists :supersede)
      (format output ""))
    (with-open-file (cache query-file
                           :direction :output
                           :if-exists :supersede)
      (format cache "~a~%" query))
    (sb-ext:run-program (namestring *server-binary*)
                        (list (namestring *dataset-path*) 
                              (namestring query-file)
                              (namestring output-file))
                        :output *standard-output* :wait t)
    (with-open-file (input output-file
                           :direction :input)
      (loop for solution = (read input nil nil)
         while solution
         collect (json "gear" (json-armor-object (getf solution :gear))
                       "head" (json-armor-object (getf solution :head))
                       "body" (json-armor-object (getf solution :body))
                       "hands" (json-armor-object (getf solution :hands))
                       "waist" (json-armor-object (getf solution :waist))
                       "feet" (json-armor-object (getf solution :feet))
                       "amulet" (json-amulet-object (getf solution :amulet))
                       "defense" (getf solution :defense)
                       "jewelPlans" 
                       (loop for jewel-plan in (getf solution :jewel-plans)
                          collect (json "active" (getf jewel-plan :active)
                                        "plan" (loop for jewel in 
                                                    (getf jewel-plan :plan)
                                                  collect (json "name" (getf jewel :name)
                                                                "num" (getf jewel :quantity))))))))))


(def-global-code skill-systems
  (with-open-file (in (merge-pathnames "skills.lisp"
                                       *dataset-path*)
                      :direction :input)
    `(array 
      ,@(loop for skill-system in (read in)
           collect `(create :name ,(getf skill-system :system-name)
			    :skills (array ,@(loop for skill in (getf skill-system 
								      :skills)
						when (> (getf skill :points) 0)
						collect `(create :name ,(getf skill :name)
								 :points ,(getf skill :points)))))))))

(def-widget skill-item (skill-id update-callback destructor)
    ()
  #jsx(with-slots (name skills) (aref skill-systems skill-id)
	(:li ((class-name "list-group-item"))
	     (:div ((class-name "row"))
		   (:div ((class-name "col-md-4"))
			 name)
		   (:div ((class-name "col-md-6"))
			 (:select ((class-name "form-control")
				   (on-click (lambda (e)
					       (funcall update-callback
							skill-id 
							(@ e target value)))))
				  (chain skills 
					 (map (lambda (skill id)
						(:option ((value id))
							 (@ skill name)))))))
		   (:div ((class-name "col-md-2"))
			 (:button ((class-name "btn btn-default")
				   (on-click (lambda () 
					       (funcall destructor skill-id))))
				  (:span ((class-name "glyphicon glyphicon-remove")))))))))

(def-widget skill-panel (language change-callback)
    ((state (effects (array))
	    (selected 0))
     (add-skill ()
		(funcall change-callback (local-state selected) 0)
		(let ((new-effects (local-state effects)))
		  (chain new-effects (push (local-state selected)))
		  (chain this (set-state (create effects new-effects))))
		nil)
     (remove-skill (skill-id)
		   (funcall change-callback skill-id -1)
		   (let ((new-effects (local-state effects)))
		     (setf new-effects
			   (chain new-effects (filter (lambda (e i a) 
							(!= e skill-id)))))
		     (chain this (set-state (create effects new-effects))))
		   nil))
  #jsx(:div ((class-name "panel panel-default"))
            (:div ((class-name "panel-heading"))
                  (lang-text ("en" "Skills")
                             ("zh" "技能")))
            (:ul ((class-name "list-group"))
		 (chain (local-state effects)
			(map (lambda (skill-id) 
			       (:skill-item ((skill-id skill-id)
					     (update-callback change-callback)
					     (destructor (@ this remove-skill))))))))
            (:div ((class-name "panel-body"))
                  (:div ((class-name "input-group"))
                        (:select ((class-name "form-control")
				  (on-click (lambda (e)
					      (setf (local-state selected) 
						    (@ e target value)))))
				 (chain skill-systems 
					(map (lambda (system id)
					       (:option ((value id)) (@ system name))))))
                        (:div ((class-name "input-group-btn dropdown"))
                              (:button ((class-name "btn btn-default")
					(on-click (@ this add-skill)))
                                       (lang-text ("en" "Add")
                                                  ("zh" "添加"))))))))

(def-widget amulet-skill-panel (language skill-id skill-points slot-id callback)
    ()
  #jsx(:div ((class-name "form-inline")
             (style :margin-bottom "20px"))
            (:div ((class-name "form-group")
                   (style :margin-right "20px"))
                  (:select ((class-name "form-control")
                            (value skill-id)
                            (on-change (lambda (e)
                                         (funcall callback slot-id
                                                  "skill-id" (@ e target value)))))
                           (:option ((value "-1")) (lang-text ("en" "Blank")
                                                              ("zh" "无技能")))
                           (chain skill-systems 
                                  (map (lambda (system id)
                                         (:option ((value id)) (@ system name)))))))
            (:div ((class-name "form-group"))
                  (:select ((class-name "form-control")
                            (value skill-points)
                            (on-change (lambda (e)
                                         (funcall callback slot-id
                                                  "points" (@ e target value)))))
                           (chain (array -10 -9 -8 -7 -6 -5 -4 -3 -2 -1 0 
                                         1 2 3 4 5 6 7 8 9 10 11 12 13 14
                                         15 16 17 18 19 20)
                                  (map (lambda (points)
                                         (:option ((value points))
                                                  (if (> points 0) 
                                                      (+ "+" points)
                                                      points)))))))))

(def-widget amulet-item (language amulet destructor)
    ()                    
  #jsx(:li ((class-name "list-group-item"))
           (:div ((class-name "row"))
                 (:div ((class-name "col-md-2")
                        (style :font-family "monospace"))
                       (funcall (lambda (x) (case x
                                              ("0" "---")
                                              ("1" "o--")
                                              ("2" "oo-")
                                              ("3" "ooo")))
                                (aref amulet 0)))
                 (:div ((class-name "col-md-4"))
                         (when (> (@ amulet length) 1)
                           (let ((content ""))
                             (setf content (+ content (@ (aref skill-systems 
                                                               (aref amulet 1))
                                                         name)))
                             (let ((points (aref amulet 2)))
                               (setf content (+ content (if (> points 0) 
                                                            (+ " +" points)
                                                            (+ " " points)))))
                             content)))
                 (:div ((class-name "col-md-4"))
                       (let ((content ""))
                         (when (> (@ amulet length) 3)
                           (setf content (+ content (@ (aref skill-systems 
                                                             (aref amulet 3))
                                                       name)))
                           (let ((points (aref amulet 4)))
                             (setf content (+ content (if (> points 0) 
                                                          (+ " +" points)
                                                          (+ " " points)))))
                           content)))
                 (:div ((class-name "col-md-2"))
                       (:button ((class-name "btn btn-default btn-xs")
                                 (on-click (lambda () 
                                             (funcall destructor amulet))))
                                (:span ((class-name "glyphicon glyphicon-remove"))))))))

(def-widget amulet-panel (language callback)
    ((state (amulets (array))
            (holes "0")
            (skill-points-a 0)
            (skill-points-b 0)
            (skill-id-a -1)
            (skill-id-b -1))
     (add-amulet ()
                 (let ((amulet (array)))
                   (chain amulet (push (local-state holes)))
                   (when (and (!= (local-state skill-points-a) 0)
                              (!= (local-state skill-id-a) -1))
                     (chain amulet (push (local-state skill-id-a)))
                     (chain amulet (push (local-state skill-points-a))))
                   (when (and (!= (local-state skill-points-b) 0)
                              (!= (local-state skill-id-b) -1))
                     (chain amulet (push (local-state skill-id-b)))
                     (chain amulet (push (local-state skill-points-b))))
                   (when (or (> (@ amulet length) 1)
                             (> (aref amulet 0) 0))
                     (let ((new-amulets (local-state amulets)))
                       (chain new-amulets (push amulet))
                       (chain this (set-state (create amulets new-amulets
                                                      holes "0"
                                                      skill-points-a 0
                                                      skill-points-b 0
                                                      skill-id-a -1
                                                      skill-id-b -1))))
                     (funcall callback new-amulets))))
     (stringify (amulet)
                (let ((result ""))
                  (loop for x in amulet
                     do (setf result (+ result "," x)))
                  result))
     (remove-amulet (amulet)
                    (let ((new-amulets 
                           (chain (local-state amulets)
                                  (filter (lambda (e index a)
                                            (!= (stringify e)
                                                (stringify amulet)))))))
                      (chain this (set-state (create amulets new-amulets)))
                      (funcall callback new-amulets))
                    nil)
     (handle-holes (holes)
                   (chain this (set-state (create holes holes)))
                   nil)
     (handle-change (slot-id type value)
                    (if (= type "points")
                        (if (= slot-id "a")
                            (chain this (set-state (create skill-points-a value)))
                            (chain this (set-state (create skill-points-b value))))
                        (if (= slot-id "a")
                            (chain this (set-state (create skill-id-a value)))
                            (chain this (set-state (create skill-id-b value)))))
                    nil))
  #jsx(:div ((class-name "panel panel-default"))
            (:div ((class-name "panel-heading"))
                  (lang-text ("en" "Amulets")
                             ("zh" "护石")))
            (:ul ((class-name "list-group"))
                 (chain (local-state amulets)
                        (map (lambda (amulet)
                               (:amulet-item ((:language language)
                                              (:destructor (@ this remove-amulet))
                                              (:amulet amulet)))))))
            (:div ((class-name "panel-body"))
                  (:label () (lang-text ("en" "Skill A")
                                        ("zh" "技能 1")))
                  (:amulet-skill-panel ((:language language)
                                        (skill-id (local-state skill-id-a))
                                        (skill-points (local-state skill-points-a))
                                        (slot-id "a")
                                        (:callback (@ this handle-change))))
                  (:label () (lang-text ("en" "Skill B")
                                        ("zh" "技能 2")))
                  (:amulet-skill-panel ((:language language)
                                        (skill-id (local-state skill-id-b))
                                        (skill-points (local-state skill-points-b))
                                        (slot-id "b")
                                        (:callback (@ this handle-change))))
                  (:label () (lang-text ("en" "Holes")
                                        ("zh" "护石孔数")))
                  (:select ((class-name "form-control")
                            (value (local-state holes))
                            (style :margin-bottom "20px")
                            (on-change (lambda (e)
                                         (funcall (@ this handle-holes)
                                                  (@ e target value)))))
                           (:option ((value "0")) "---")
                           (:option ((value "1")) "O")
                           (:option ((value "2")) "OO")
                           (:option ((value "3")) "OOO"))
                  (:button ((class-name "btn btn-default")
                            (on-click (@ this add-amulet)))
                           (lang-text ("en" "Add")
                                      ("zh" "添加"))))))
                           

(def-widget parameter-panel (language callback)
    ()
  #jsx(:div ((class-name "row"))
            (:div ((class-name "col-md-2"))
                  (:div ((class-name "panel panel-default"))
                        (:div ((class-name "panel-heading"))
                              (:h3 ((class-name "panel-title"))
                                   (lang-text ("en" "Weapon Type")
                                              ("zh" "武器类型"))))
                        (:div ((class-name "panel-body"))
                              (:select ((class-name "form-control")
                                        (on-click (lambda (e)
                                                    (funcall callback "weapon-type"
                                                             (@ e target value)))))
                                       (:option ((value "melee"))
                                                (lang-text ("en" "Melee")
                                                           ("zh" "近战")))
                                       (:option ((value "range")) 
                                                (lang-text ("en" "Range")
                                                           ("zh" "远程")))))))
            (:div ((class-name "col-md-2"))
                  (:div ((class-name "panel panel-default"))
                        (:div ((class-name "panel-heading"))
                              (:h3 ((class-name "panel-title"))
                                   (lang-text ("en" "Weapon Holes")
                                              ("zh" "武器孔数"))))
                        (:div ((class-name "panel-body"))
                              (:select ((class-name "form-control")
                                        (on-click (lambda (e)
                                                    (funcall callback "weapon-holes"
                                                             (@ e target value)))))
                                       (:option ((value "0")) "---")
                                       (:option ((value "1")) "O")
                                       (:option ((value "2")) "OO")
                                       (:option ((value "3")) "OOO")))))
            (:div ((class-name "col-md-2"))
                  (:div ((class-name "panel panel-default"))
                        (:div ((class-name "panel-heading"))
                              (:h3 ((class-name "panel-title"))
                                   (lang-text ("en" "Minimum Rare")
                                              ("zh" "稀有度"))))
                        (:div ((class-name "panel-body"))
                              (:select ((class-name "form-control")
                                        (on-click (lambda (e)
                                                    (funcall callback "rare"
                                                             (@ e target value)))))
                                       (:option ((value "1")) "1")
                                       (:option ((value "2")) "2")
                                       (:option ((value "3")) "3")
                                       (:option ((value "4")) "4")
                                       (:option ((value "5")) "5")
                                       (:option ((value "6")) "6")
                                       (:option ((value "7")) "7")
                                       (:option ((value "8")) "8")
                                       (:option ((value "9")) "9")
                                       (:option ((value "10")) "10")))))))

(def-widget armor-display (language part name material holes rare
                                    id appender filter)
    ()
  #jsx(:li ((class-name "list-group-item"))
           (:div ((class-name "input-group"))
                 (:span ((class-name "input-group-addon"))
                        (:img ((src (+ "img/" part ".png"))
                               (:style :height "65%"))))
                 (:span ((class-name "input-group-addon")
                         (style :font-family "monospace"))
                        rare)
                 (:span ((class-name "input-group-addon")
                         (style :font-family "monospace"
                                :font-size "130%"))
                        (funcall (lambda (x) (case x
                                               (0 "---")
                                               (1 "o--")
                                               (2 "oo-")
                                               (3 "ooo")))
                                 holes))
                 (:input ((type "text")
                          ("data-toggle" "tooltip")
                          ("data-placement" "left")
                          (title material)
                          (style :padding-left "40px")
                          (class-name "form-control")
                          (readonly "readonly")
                          (value name))
                 (:div ((class-name "input-group-btn"))
                       (:button ((class-name "btn btn-default")
                                 ("data-toggle" "tooltip")
                                 ("data-placement" "left")
                                 (title (lang-text ("en" "filter by blacklisting this")
                                                   ("zh" "过滤掉包含此装备的配装")))
                                 (on-click (lambda ()
                                             (when (and (!= part "gear")
                                                        (!= part "amulet"))
                                               (funcall appender id)
                                               (funcall filter true))
                                             nil)))
                                (:span ((class-name "glyphicon glyphicon-remove-sign")))))))))

(def-widget armor-set-display (language armor-set blacklist-callback filter-callback)
    ((state (jewel-plan-id 0))
     (switch-jewel-plan (id)
                        (chain this (set-state (create jewel-plan-id
                                                       id)))))
  #jsx(:div ((class-name "panel panel-success"))
            (:div ((class-name "panel-heading"))
                  (lang-text ("en" "Armor Set")
                             ("zh" "配装组合")))
            (:ul ((class-name "list-group"))
                 (:armor-display ((part "gear")
                                  (:language language)
                                  (name (@ armor-set gear name))
                                  (material "")
                                  (rare "??")
                                  (holes (@ armor-set gear holes))))
                 (:armor-display ((part "head")
                                  (:language language)
                                  (:id (@ armor-set head id))
                                  (:appender blacklist-callback)
                                  (:filter filter-callback)
                                  (name (@ armor-set head name))
                                  (material (@ armor-set head material))
                                  (rare (@ armor-set head rare))
                                  (holes (@ armor-set head holes))))
                 (:armor-display ((part "body")
                                  (:language language)
                                  (:id (@ armor-set body id))
                                  (:appender blacklist-callback)
                                  (:filter filter-callback)
                                  (name (@ armor-set body name))
                                  (material (@ armor-set body material))
                                  (rare (@ armor-set body rare))
                                  (holes (@ armor-set body holes))))
                 (:armor-display ((part "hands")
                                  (:language language)
                                  (:id (@ armor-set hands id))
                                  (:appender blacklist-callback)
                                  (:filter filter-callback)
                                  (name (@ armor-set hands name))
                                  (material (@ armor-set hands material))
                                  (rare (@ armor-set hands rare))
                                  (holes (@ armor-set hands holes))))
                 (:armor-display ((part "waist")
                                  (:language language)
                                  (:id (@ armor-set waist id))
                                  (:appender blacklist-callback)
                                  (:filter filter-callback)
                                  (name (@ armor-set waist name))
                                  (material (@ armor-set waist material))
                                  (rare (@ armor-set waist rare))
                                  (holes (@ armor-set waist holes))))
                 (:armor-display ((part "feet")
                                  (:language language)
                                  (:id (@ armor-set feet id))
                                  (:appender blacklist-callback)
                                  (:filter filter-callback)
                                  (name (@ armor-set feet name))
                                  (material (@ armor-set feet material))
                                  (rare (@ armor-set feet rare))
                                  (holes (@ armor-set feet holes))))
                 (:armor-display ((part "amulet")
                                  (:language language)
                                  (name (@ armor-set amulet name))
                                  (material (@ armor-set amulet material))
                                  (rare "??")
                                  (holes (@ armor-set amulet holes)))))
            (:div ((class-name "panel-body"))
                  (:div ()
                        (:nav () 
                              (:ul ((class-name "pagination"))
                                   (:li ((class-name "disabled"))
                                        (:a ()
                                            (lang-text ("en" "Decorations Plan")
                                                       ("zh" "装饰珠方案"))))
                                   (chain (@ armor-set jewel-plans)
                                          (map (lambda (x id)
                                                 (if (= id (local-state jewel-plan-id))
                                                     (:li ((class-name "active")
                                                           (on-click 
                                                            (lambda ()
                                                              (funcall (@ this switch-jewel-plan)
                                                                       id))))
                                                          (:a () (1+ id)))
                                                     (:li ((on-click 
                                                            (lambda ()
                                                              (funcall (@ this switch-jewel-plan)
                                                                       id))))
                                                          (:a () (1+ id))))))))))
                  (:p () (+ (lang-text ("en" "Defense: " )
                                       ("zh" "防御力: "))
                            (@ armor-set defense)))
                  (:p () (let ((content (lang-text ("en" "Active: ")
                                                   ("zh" "发动技能: ")))
                               (skills (@ (aref (@ armor-set jewel-plans)
                                                (local-state jewel-plan-id))
                                          active)))
                           (loop for skill in skills
                              do (setf content (+ content skill "  |  ")))
                           content))
                  (:div () (let ((plan (@ (aref (@ armor-set jewel-plans)
                                                (local-state jewel-plan-id))
                                          plan)))
                             (chain plan 
                                    (map (lambda (x)
                                           (:div () (:span ((class-name "label label-warning"))
                                                           (@ x name) " x " (@ x num)))))))))))

(def-widget title-bar (language callback)
    ()
  #jsx(:div ((class-name "topbar")
             (style :width "auto"
                    :margin "auto"))
            (:div ((class-name "fill row"))
                  (:div ((class-name "col-md-6"))
                        (:div ((class-name "page-header"))
                              (:h1 () (lang-text ("en" "MH4G Armor Tool")
                                                 ("zh" "怪物猎人4G 配装器")))))
                  (:div ((class-name "col-md-2 col-md-offset-4"))
                        (:select ((class-name "form-control")
                                  (on-click (lambda (e)
                                              (funcall callback
                                                       (@ e target value)))))
                                 (:option ((value "en")) "English")
                                 (:option ((value "zh")) "中文"))))))

(def-widget info-panel (language)
    ()
  #jsx(:div ()
            (:p () "Built by "
                (:a ((href "https://github.com/breakds")) "BreakDS")
                ", with "
                (:a ((href "https://github.com/breakds/realispic")) "reaLISPic")
                ", "
                (:a ((href "http://www.sbcl.org")) "SBCL")
                "and "
                (:a ((href "http://getbootstrap.com/")) "Twitter Bootstrap")
                ".")
            (:p () "Deisgn and artwork by Cassandra Qi.")))

(def-widget app-view ()
    ((state (language "en")
            (weapon-type "melee")
            (weapon-holes 0)
            (rare 1)
            (amulets (array))
	    (effects (array))
            (blacklist (array))
            (query-fail false)
            (query-result (array)))
     (switch-language (target) 
                      (chain this (set-state (create language target))))
     (append-blacklist (id)
                       (let ((new-blacklist (local-state blacklist)))
                         (chain new-blacklist (push id))
                         (chain this (set-state (create blacklist
                                                        new-blacklist))))
                       nil)
     (handle-query (is-filter)
                   (let ((query ""))
                     (setf query (+ query "(:weapon-type \""
                                    (local-state weapon-type) "\") "))
                     (setf query (+ query "(:weapon-holes "
                                    (local-state weapon-holes) ") "))
                     (setf query (+ query "(:rare "
                                    (local-state rare) ") "))
                     (loop for effect in (local-state effects)
                        do (setf query (+ query "(:skill "
                                          (@ effect id) " "
                                          (@ effect points) ") ")))
                     (loop for amulet in (local-state amulets)
                        do (progn (setf query (+ query "(:amulet " 
                                                 (aref amulet 0)
                                                 " ("))
                                  (when (> (@ amulet length) 1)
                                    (setf query (+ query (aref amulet 1)))
                                    (loop for i from 2 below (@ amulet length)
                                       do (setf query (+ query " "
                                                         (aref amulet i)))))
                                  (setf query (+ query ")) "))))
                     ;; blacklist
                     (when (not is-filter)
                       (chain this (set-state (create blacklist (array)))))
                     (when (and (> (@ (local-state blacklist) length) 0)
                                is-filter)
                       (setf query (+ query "(:blacklist ("
                                      (aref (local-state blacklist) 0)))
                       (loop for i from 1 
                          below (@ (local-state blacklist) length)
                          do (setf query (+ query " " 
                                            (aref (local-state blacklist) i))))
                       (setf query (+ query ")) ")))
                     (chain console (log query))
                     (with-rpc (answer-query query)
                       (chain this (set-state (create query-result rpc-result
                                                      query-fail (<= (@ rpc-result length) 0))))
                       (chain console (log rpc-result))))
                   nil)
     (update-parameters (param value)
                        (if (= param "weapon-type")
                            (chain this (set-state (create weapon-type value)))
                            (if (= param "weapon-holes")
                                (chain this (set-state (create weapon-holes value)))
                                (if (= param "rare")
                                    (chain this (set-state (create rare value))))))
                        nil)
     (update-amulets (new-amulets)
                     (chain this (set-state (create amulets new-amulets)))
                     nil)
     (update-effects (skill-id active-id)
		     (let ((new-effects (local-state effects)))
		       (setf new-effects
			     (chain new-effects (filter (lambda (e i a) 
							  (!= (@ e id)
							      skill-id)))))
		       (when (> active-id -1)
			 (let ((points (@ (aref (@ (aref skill-systems skill-id) skills)
						active-id) points)))
			   (chain new-effects (push (create :id skill-id
							    :points points)))))
		       (chain this (set-state (create effects new-effects))))
		     nil))
  #jsx(:div ((style :margin "20px 50px 30px 50px"))
            (:title-bar ((language (@ this state language))
                         (callback (@ this switch-language))))
            (:parameter-panel ((language (@ this state language))
                               (callback (@ this update-parameters))))
            (:div ((class-name "row"))
                  (:div ((class-name "col-md-3"))
                        (:amulet-panel ((:language (@ this state language))
                                        (:callback (@ this update-amulets))))
                        (:info-panel ((:language (@ this state language)))))
                  (:div ((class-name "col-md-3"))
                        (:skill-panel ((language (@ this state language))
				       (change-callback (@ this update-effects))))
                        (:button ((class-name "btn btn-default")
                                  (on-click (lambda () 
                                              (funcall (@ this handle-query) false)
                                              nil)))
                                 (if (= (local-state "language") "en")
                                     "Search"
                                     "搜索")))
                  (:div ((class-name "col-md-3 col-md-offset-1"))
                        (if (local-state query-fail)
                            (:div ((class-name "alert alert-info"))
                                  (if (= (local-state "language") "en")
                                      "Your query does not return anything."
                                      "没有找到满足条件的配装."))
                            (chain (local-state query-result)
                                   (map (lambda (armor-set)
                                          (:armor-set-display ((language (@ this state language))
                                                               (blacklist-callback (@ this append-blacklist))
                                                               (filter-callback (@ this handle-query))
                                                               (armor-set armor-set)))))))))))


(def-realispic-app (armor-tools :title "Monster Hunter's Arsenal"
                                :port 16384
                                :css ("https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.2/css/bootstrap.min.css")
                                :libs ("http://fb.me/react-0.12.2.min.js"
                                       "https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"
                                       "https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.2/js/bootstrap.min.js")
                                :document-base (merge-pathnames "assets/"
                                                                (asdf:system-source-directory 'monster-avengers)))
  #jsx(:app-view))

(eval-when (:compile-toplevel :load-toplevel :execute)
  (disable-jsx-reader))
